create schema bd_analisis_datos2_cdattg;
use bd_analisis_datos2_cdattg;

show tables;

#drop table tabla_genericas_20222;
#drop table data_icfes_sabertyt_2022_2_cols;
describe tabla_genericas_20222;
select * from data_icfes_sabertyt_2022_2_;

truncate sabertyt_todo ;


SELECT table_schema AS "bd_analisis_datos_cdattg", 
       SUM(data_length + index_length) / 1024 / 1024 AS "Tamaño en MB" 
FROM information_schema.TABLES 
GROUP BY table_schema;


describe sabertyt_genericas_20211;
describe sabertyt_todo;

select count(*), diferencial from sabertyt_todo group by diferencial order by diferencial desc;
select count(*) from sabertyt_genericas_20222;
select count(*) from sabertyt_genericas_20221;
select count(*) from sabertyt_genericas_20212;
select count(*) from sabertyt_genericas_20211;
select count(*) from sabertyt_genericas_20202;
select count(*) from sabertyt_genericas_20201;
select count(*) from sabertyt_genericas_20192;
select count(*) from sabertyt_genericas_20191;
select count(*) from sabertyt_genericas_20182;


select SUM(estu_cod_reside_mcpio), diferencial 
from sabertyt_todo group by diferencial;

select SUM(periodo) from sabertyt_genericas_20222;
select SUM(periodo) from sabertyt_genericas_20221;
select SUM(estu_cod_reside_mcpio) from sabertyt_genericas_20212;
select SUM(estu_cod_reside_mcpio) from sabertyt_genericas_20211;
select SUM(estu_cod_reside_mcpio) from sabertyt_genericas_20202;
select SUM(estu_cod_reside_mcpio) from sabertyt_genericas_20201;
select SUM(estu_cod_reside_mcpio) from sabertyt_genericas_20192;
select SUM(estu_cod_reside_mcpio) from sabertyt_genericas_20191;
select SUM(estu_cod_reside_mcpio) from sabertyt_genericas_20182;

#-----------------------insercion final --------------------------

INSERT INTO sabertyt_todo
( 
  `ESTU_TIPODOCUMENTO`  ,
  `ESTU_NACIONALIDAD`  ,
  `ESTU_GENERO`  ,
  `ESTU_FECHANACIMIENTO`,
  `ESTU_EXTERIOR`  ,
  `PERIODO`  ,
  `ESTU_CONSECUTIVO`  ,
  `ESTU_ESTUDIANTE`  ,
  `ESTU_PAIS_RESIDE`  ,
  `ESTU_AREARESIDE`  ,
  `ESTU_DEPTO_RESIDE`  ,
  `ESTU_COD_RESIDE_DEPTO`  ,
  `ESTU_MCPIO_RESIDE`  ,
  `ESTU_COD_RESIDE_MCPIO`  ,
  `ESTU_ESTADOCIVIL`  ,
  `ESTU_VALORMATRICULAUNIVERSIDAD`  ,
  `ESTU_PAGOMATRICULABECA`  ,
  `ESTU_PAGOMATRICULACREDITO`  ,
  `ESTU_PAGOMATRICULAPADRES`  ,
  `ESTU_PAGOMATRICULAPROPIO`  ,
  `ESTU_CURSODOCENTESIES`  ,
  `ESTU_CURSOIESAPOYOEXTERNO`  ,
  `ESTU_CURSOIESEXTERNA`  ,
  `ESTU_SIMULACROTIPOICFES`  ,
  `ESTU_ACTIVIDADREFUERZOAREAS`  ,
  `ESTU_ACTIVIDADREFUERZOGENERIC`  ,
  `ESTU_TIPODOCUMENTOSB11`  ,
  `ESTU_SEMESTRECURSA`  ,
  `FAMI_EDUCACIONPADRE`  ,
  `FAMI_EDUCACIONMADRE`  ,
  `FAMI_OCUPACIONPADRE`  ,
  `FAMI_OCUPACIONMADRE`  ,
  `FAMI_ESTRATOVIVIENDA`  ,
  `FAMI_TIENEINTERNET`  ,
  `FAMI_TIENECOMPUTADOR`  ,
  `FAMI_TIENELAVADORA`  ,
  `FAMI_TIENEHORNOMICROOGAS`  ,
  `FAMI_TIENESERVICIOTV`  ,
  `FAMI_TIENEAUTOMOVIL`  ,
  `FAMI_TIENEMOTOCICLETA`  ,
  `FAMI_TIENECONSOLAVIDEOJUEGOS`  ,
  `FAMI_CUANTOSCOMPARTEBAÑO`  ,
  `ESTU_PRESENTACIONCASA`  ,
  `ESTU_HORASSEMANATRABAJA`  ,
  `FAMI_TRABAJOLABORPADRE`  ,
  `FAMI_TRABAJOLABORMADRE`  ,
  `INST_COD_INSTITUCION`  ,
  `INST_NOMBRE_INSTITUCION`  ,
  `ESTU_PRGM_ACADEMICO`  ,
  `ESTU_SNIES_PRGMACADEMICO`  ,
  `GRUPOREFERENCIA`  ,
  `ESTU_PRGM_CODMUNICIPIO`  ,
  `ESTU_PRGM_MUNICIPIO`  ,
  `ESTU_PRGM_DEPARTAMENTO`  ,
  `ESTU_NIVEL_PRGM_ACADEMICO`  ,
  `ESTU_METODO_PRGM`  ,
  `ESTU_NUCLEO_PREGRADO`  ,
  `ESTU_INST_CODMUNICIPIO`  ,
  `ESTU_INST_MUNICIPIO`  ,
  `ESTU_INST_DEPARTAMENTO`  ,
  `INST_CARACTER_ACADEMICO`  ,
  `INST_ORIGEN`  ,
  `ESTU_CODICFESCOLE_TERMINO`  ,
  `ESTU_COLE_TERMINO`  ,
  `ESTU_CODDANE_COLE_TERMINO`  ,
  `ESTU_COD_COLE_MCPIO_TERMINO`  ,
  `ESTU_COD_MCPIO_PRESENTACION`  ,
  `ESTU_MCPIO_PRESENTACION`  ,
  `ESTU_DEPTO_PRESENTACION`  ,
  `ESTU_COD_DEPTO_PRESENTACION`  ,
  `MOD_RAZONA_CUANTITAT_PUNT`  ,
  `MOD_RAZONA_CUANTITATIVO_PNAL`  ,
  `MOD_RAZONA_CUANTITATIVO_PNBC`  ,
  `MOD_LECTURA_CRITICA_PUNT`  ,
  `MOD_LECTURA_CRITICA_PNAL`  ,
  `MOD_LECTURA_CRITICA_PNBC`  ,
  `MOD_COMPETEN_CIUDADA_PUNT`  ,
  `MOD_COMPETEN_CIUDADA_PNAL`  ,
  `MOD_COMPETEN_CIUDADA_PNBC`  ,
  `MOD_INGLES_PUNT`  ,
  `MOD_INGLES_DESEM`  ,
  `MOD_INGLES_PNAL`  ,
  `MOD_INGLES_PNBC`  ,
  `MOD_COMUNI_ESCRITA_PUNT`  ,
  `MOD_COMUNI_ESCRITA_DESEM`  ,
  `MOD_COMUNI_ESCRITA_PNAL`  ,
  `MOD_COMUNI_ESCRITA_PNBC`  ,
  `PUNT_GLOBAL`  ,
  `PERCENTIL_NBC`  ,
  `PERCENTIL_GLOBAL`  ,
  `ESTU_ESTADOINVESTIGACION`  ,
  ESTU_TIENEETNIA,
  ESTU_ETNIA,
  diferencial
)
SELECT
`ESTU_TIPODOCUMENTO`  ,
  `ESTU_NACIONALIDAD`  ,
  `ESTU_GENERO`  ,
  `ESTU_FECHANACIMIENTO`,
  `ESTU_EXTERIOR`  ,
  `PERIODO`  ,
  `ESTU_CONSECUTIVO`  ,
  `ESTU_ESTUDIANTE`  ,
  `ESTU_PAIS_RESIDE`  ,
  `ESTU_AREARESIDE`  ,
  `ESTU_DEPTO_RESIDE`  ,
  `ESTU_COD_RESIDE_DEPTO`  ,
  `ESTU_MCPIO_RESIDE`  ,
  `ESTU_COD_RESIDE_MCPIO`  ,
  `ESTU_ESTADOCIVIL`  ,
  `ESTU_VALORMATRICULAUNIVERSIDAD`  ,
  `ESTU_PAGOMATRICULABECA`  ,
  `ESTU_PAGOMATRICULACREDITO`  ,
  `ESTU_PAGOMATRICULAPADRES`  ,
  `ESTU_PAGOMATRICULAPROPIO`  ,
  `ESTU_CURSODOCENTESIES`  ,
  `ESTU_CURSOIESAPOYOEXTERNO`  ,
  `ESTU_CURSOIESEXTERNA`  ,
  `ESTU_SIMULACROTIPOICFES`  ,
  `ESTU_ACTIVIDADREFUERZOAREAS`  ,
  `ESTU_ACTIVIDADREFUERZOGENERIC`  ,
  `ESTU_TIPODOCUMENTOSB11`  ,
  NULL, #`ESTU_SEMESTRECURSA`  ,
  `FAMI_EDUCACIONPADRE`  ,
  `FAMI_EDUCACIONMADRE`  ,
  NULL, #`FAMI_OCUPACIONPADRE`  ,
  NULL, #`FAMI_OCUPACIONMADRE`  ,
  `FAMI_ESTRATOVIVIENDA`  ,
  `FAMI_TIENEINTERNET`  ,
  `FAMI_TIENECOMPUTADOR`  ,
  `FAMI_TIENELAVADORA`  ,
  `FAMI_TIENEHORNOMICROOGAS`  ,
  `FAMI_TIENESERVICIOTV`  ,
  `FAMI_TIENEAUTOMOVIL`  ,
  `FAMI_TIENEMOTOCICLETA`  ,
  `FAMI_TIENECONSOLAVIDEOJUEGOS`  ,
  `FAMI_CUANTOSCOMPARTEBAÑO`  ,
  NULL, #`ESTU_PRESENTACIONCASA`  ,
  `ESTU_HORASSEMANATRABAJA`  ,
  `FAMI_TRABAJOLABORPADRE`  ,
  `FAMI_TRABAJOLABORMADRE`  ,
  `INST_COD_INSTITUCION`  ,
  `INST_NOMBRE_INSTITUCION`  ,
  `ESTU_PRGM_ACADEMICO`  ,
  `ESTU_SNIES_PRGMACADEMICO`  ,
  `GRUPOREFERENCIA`  ,
  `ESTU_PRGM_CODMUNICIPIO`  ,
  `ESTU_PRGM_MUNICIPIO`  ,
  `ESTU_PRGM_DEPARTAMENTO`  ,
  `ESTU_NIVEL_PRGM_ACADEMICO`  ,
  `ESTU_METODO_PRGM`  ,
  `ESTU_NUCLEO_PREGRADO`  ,
  `ESTU_INST_CODMUNICIPIO`  ,
  `ESTU_INST_MUNICIPIO`  ,
  `ESTU_INST_DEPARTAMENTO`  ,
  `INST_CARACTER_ACADEMICO`  ,
  `INST_ORIGEN`  ,
  NULL, #`ESTU_CODICFESCOLE_TERMINO`  ,
  `ESTU_COLE_TERMINO`  ,
  `ESTU_CODDANE_COLE_TERMINO`  ,
  `ESTU_COD_COLE_MCPIO_TERMINO`  ,
  `ESTU_COD_MCPIO_PRESENTACION`  ,
  `ESTU_MCPIO_PRESENTACION`  ,
  `ESTU_DEPTO_PRESENTACION`  ,
  `ESTU_COD_DEPTO_PRESENTACION`  ,
  `MOD_RAZONA_CUANTITAT_PUNT`  ,
  `MOD_RAZONA_CUANTITATIVO_PNAL`  ,
  NULL, #`MOD_RAZONA_CUANTITATIVO_PNBC`  ,
  `MOD_LECTURA_CRITICA_PUNT`  ,
  `MOD_LECTURA_CRITICA_PNAL`  ,
  NULL, #`MOD_LECTURA_CRITICA_PNBC`  ,
  `MOD_COMPETEN_CIUDADA_PUNT`  ,
  `MOD_COMPETEN_CIUDADA_PNAL`  ,
  NULL, #`MOD_COMPETEN_CIUDADA_PNBC`  ,
  `MOD_INGLES_PUNT`  ,
  `MOD_INGLES_DESEM`  ,
  `MOD_INGLES_PNAL`  ,
  NULL, #`MOD_INGLES_PNBC`  ,
  `MOD_COMUNI_ESCRITA_PUNT`  ,
  `MOD_COMUNI_ESCRITA_DESEM`  ,
  `MOD_COMUNI_ESCRITA_PNAL`  ,
  NULL, #`MOD_COMUNI_ESCRITA_PNBC`  ,
  `PUNT_GLOBAL`  ,
  NULL, #`PERCENTIL_NBC`  ,
  `PERCENTIL_GLOBAL`  ,
  `ESTU_ESTADOINVESTIGACION`  ,
  '20182'
FROM sabertyt_genericas_20182
where 1 = 2;



ALTER TABLE `sabertyt_todo`  
ADD `FAMI_PERSONASHOGAR` VARCHAR(200) NULL  
AFTER `FAMI_NUMPERSONASACARGO`,  
ADD `FAMI_CUARTOSHOGAR` VARCHAR(200) NULL  
AFTER `FAMI_PERSONASHOGAR`;



#Esta importación solo sirve para el 2019 en adelante.
#Algunos campos de las etnias se pierden a partir de aquí.
INSERT INTO sabertyt_todo
( 
  `ESTU_TIPODOCUMENTO`  ,
  `ESTU_NACIONALIDAD`  ,
  `ESTU_GENERO`  ,
  `ESTU_FECHANACIMIENTO`,
  `ESTU_EXTERIOR`  ,
  `PERIODO`  ,
  `ESTU_CONSECUTIVO`  ,
  `ESTU_ESTUDIANTE`  ,
  `ESTU_PAIS_RESIDE`  ,
  `ESTU_AREARESIDE`  ,
  `ESTU_DEPTO_RESIDE`  ,
  `ESTU_COD_RESIDE_DEPTO`  ,
  `ESTU_MCPIO_RESIDE`  ,
  `ESTU_COD_RESIDE_MCPIO`  ,
  `ESTU_ESTADOCIVIL`  ,
  `ESTU_VALORMATRICULAUNIVERSIDAD`  ,
  `ESTU_PAGOMATRICULABECA`  ,
  `ESTU_PAGOMATRICULACREDITO`  ,
  `ESTU_PAGOMATRICULAPADRES`  ,
  `ESTU_PAGOMATRICULAPROPIO`  ,
  `ESTU_CURSODOCENTESIES`  ,
  `ESTU_CURSOIESAPOYOEXTERNO`  ,
  `ESTU_CURSOIESEXTERNA`  ,
  `ESTU_SIMULACROTIPOICFES`  ,
  `ESTU_ACTIVIDADREFUERZOAREAS`  ,
  `ESTU_ACTIVIDADREFUERZOGENERIC`  ,
  `ESTU_TIPODOCUMENTOSB11`  ,
  `ESTU_SEMESTRECURSA`  ,
  `FAMI_EDUCACIONPADRE`  ,
  `FAMI_EDUCACIONMADRE`  ,
  `FAMI_OCUPACIONPADRE`  ,
  `FAMI_OCUPACIONMADRE`  ,
  `FAMI_ESTRATOVIVIENDA`  ,
  `FAMI_TIENEINTERNET`  ,
  `FAMI_TIENECOMPUTADOR`  ,
  `FAMI_TIENELAVADORA`  ,
  `FAMI_TIENEHORNOMICROOGAS`  ,
  `FAMI_TIENESERVICIOTV`  ,
  `FAMI_TIENEAUTOMOVIL`  ,
  `FAMI_TIENEMOTOCICLETA`  ,
  `FAMI_TIENECONSOLAVIDEOJUEGOS`  ,
  `FAMI_CUANTOSCOMPARTEBAÑO`  ,
  `ESTU_PRESENTACIONCASA`  ,
  `ESTU_HORASSEMANATRABAJA`  ,
  `FAMI_TRABAJOLABORPADRE`  ,
  `FAMI_TRABAJOLABORMADRE`  ,
  `INST_COD_INSTITUCION`  ,
  `INST_NOMBRE_INSTITUCION`  ,
  `ESTU_PRGM_ACADEMICO`  ,
  `ESTU_SNIES_PRGMACADEMICO`  ,
  `GRUPOREFERENCIA`  ,
  `ESTU_PRGM_CODMUNICIPIO`  ,
  `ESTU_PRGM_MUNICIPIO`  ,
  `ESTU_PRGM_DEPARTAMENTO`  ,
  `ESTU_NIVEL_PRGM_ACADEMICO`  ,
  `ESTU_METODO_PRGM`  ,
  `ESTU_NUCLEO_PREGRADO`  ,
  `ESTU_INST_CODMUNICIPIO`  ,
  `ESTU_INST_MUNICIPIO`  ,
  `ESTU_INST_DEPARTAMENTO`  ,
  `INST_CARACTER_ACADEMICO`  ,
  `INST_ORIGEN`  ,
  `ESTU_CODICFESCOLE_TERMINO`  ,
  `ESTU_COLE_TERMINO`  ,
  `ESTU_CODDANE_COLE_TERMINO`  ,
  `ESTU_COD_COLE_MCPIO_TERMINO`  ,
  `ESTU_COD_MCPIO_PRESENTACION`  ,
  `ESTU_MCPIO_PRESENTACION`  ,
  `ESTU_DEPTO_PRESENTACION`  ,
  `ESTU_COD_DEPTO_PRESENTACION`  ,
  `MOD_RAZONA_CUANTITAT_PUNT`  ,
  `MOD_RAZONA_CUANTITATIVO_PNAL`  ,
  `MOD_RAZONA_CUANTITATIVO_PNBC`  ,
  `MOD_LECTURA_CRITICA_PUNT`  ,
  `MOD_LECTURA_CRITICA_PNAL`  ,
  `MOD_LECTURA_CRITICA_PNBC`  ,
  `MOD_COMPETEN_CIUDADA_PUNT`  ,
  `MOD_COMPETEN_CIUDADA_PNAL`  ,
  `MOD_COMPETEN_CIUDADA_PNBC`  ,
  `MOD_INGLES_PUNT`  ,
  `MOD_INGLES_DESEM`  ,
  `MOD_INGLES_PNAL`  ,
  `MOD_INGLES_PNBC`  ,
  `MOD_COMUNI_ESCRITA_PUNT`  ,
  `MOD_COMUNI_ESCRITA_DESEM`  ,
  `MOD_COMUNI_ESCRITA_PNAL`  ,
  `MOD_COMUNI_ESCRITA_PNBC`  ,
  `PUNT_GLOBAL`  ,
  `PERCENTIL_NBC`  ,
  `PERCENTIL_GLOBAL`  ,
  `ESTU_ESTADOINVESTIGACION`  ,
  diferencial
)
SELECT
`ESTU_TIPODOCUMENTO`  ,
  `ESTU_NACIONALIDAD`  ,
  `ESTU_GENERO`  ,
  `ESTU_FECHANACIMIENTO`,
  `ESTU_EXTERIOR`  ,
  `PERIODO`  ,
  `ESTU_CONSECUTIVO`  ,
  `ESTU_ESTUDIANTE`  ,
  `ESTU_PAIS_RESIDE`  ,
  `ESTU_AREARESIDE`  ,
  `ESTU_DEPTO_RESIDE`  ,
  `ESTU_COD_RESIDE_DEPTO`  ,
  `ESTU_MCPIO_RESIDE`  ,
  `ESTU_COD_RESIDE_MCPIO`  ,
  `ESTU_ESTADOCIVIL`  ,
  `ESTU_VALORMATRICULAUNIVERSIDAD`  ,
  `ESTU_PAGOMATRICULABECA`  ,
  `ESTU_PAGOMATRICULACREDITO`  ,
  `ESTU_PAGOMATRICULAPADRES`  ,
  `ESTU_PAGOMATRICULAPROPIO`  ,
  `ESTU_CURSODOCENTESIES`  ,
  `ESTU_CURSOIESAPOYOEXTERNO`  ,
  `ESTU_CURSOIESEXTERNA`  ,
  `ESTU_SIMULACROTIPOICFES`  ,
  `ESTU_ACTIVIDADREFUERZOAREAS`  ,
  `ESTU_ACTIVIDADREFUERZOGENERIC`  ,
  `ESTU_TIPODOCUMENTOSB11`  ,
  `ESTU_SEMESTRECURSA`  ,
  `FAMI_EDUCACIONPADRE`  ,
  `FAMI_EDUCACIONMADRE`  ,
  `FAMI_OCUPACIONPADRE`  ,
  `FAMI_OCUPACIONMADRE`  ,
  `FAMI_ESTRATOVIVIENDA`  ,
  `FAMI_TIENEINTERNET`  ,
  `FAMI_TIENECOMPUTADOR`  ,
  `FAMI_TIENELAVADORA`  ,
  `FAMI_TIENEHORNOMICROOGAS`  ,
  `FAMI_TIENESERVICIOTV`  ,
  `FAMI_TIENEAUTOMOVIL`  ,
  `FAMI_TIENEMOTOCICLETA`  ,
  `FAMI_TIENECONSOLAVIDEOJUEGOS`  ,
  `FAMI_CUANTOSCOMPARTEBAÑO`  ,
  `ESTU_PRESENTACIONCASA`  ,
  `ESTU_HORASSEMANATRABAJA`  ,
  `FAMI_TRABAJOLABORPADRE`  ,
  `FAMI_TRABAJOLABORMADRE`  ,
  `INST_COD_INSTITUCION`  ,
  `INST_NOMBRE_INSTITUCION`  ,
  `ESTU_PRGM_ACADEMICO`  ,
  `ESTU_SNIES_PRGMACADEMICO`  ,
  `GRUPOREFERENCIA`  ,
  `ESTU_PRGM_CODMUNICIPIO`  ,
  `ESTU_PRGM_MUNICIPIO`  ,
  `ESTU_PRGM_DEPARTAMENTO`  ,
  `ESTU_NIVEL_PRGM_ACADEMICO`  ,
  `ESTU_METODO_PRGM`  ,
  `ESTU_NUCLEO_PREGRADO`  ,
  `ESTU_INST_CODMUNICIPIO`  ,
  `ESTU_INST_MUNICIPIO`  ,
  `ESTU_INST_DEPARTAMENTO`  ,
  `INST_CARACTER_ACADEMICO`  ,
  `INST_ORIGEN`  ,
  `ESTU_CODICFESCOLE_TERMINO`  ,
  `ESTU_COLE_TERMINO`  ,
  `ESTU_CODDANE_COLE_TERMINO`  ,
  `ESTU_COD_COLE_MCPIO_TERMINO`  ,
  `ESTU_COD_MCPIO_PRESENTACION`  ,
  `ESTU_MCPIO_PRESENTACION`  ,
  `ESTU_DEPTO_PRESENTACION`  ,
  `ESTU_COD_DEPTO_PRESENTACION`  ,
  `MOD_RAZONA_CUANTITAT_PUNT`  ,
  `MOD_RAZONA_CUANTITATIVO_PNAL`  ,
  `MOD_RAZONA_CUANTITATIVO_PNBC`  ,
  `MOD_LECTURA_CRITICA_PUNT`  ,
  `MOD_LECTURA_CRITICA_PNAL`  ,
  `MOD_LECTURA_CRITICA_PNBC`  ,
  `MOD_COMPETEN_CIUDADA_PUNT`  ,
  `MOD_COMPETEN_CIUDADA_PNAL`  ,
  `MOD_COMPETEN_CIUDADA_PNBC`  ,
  `MOD_INGLES_PUNT`  ,
  `MOD_INGLES_DESEM`  ,
  `MOD_INGLES_PNAL`  ,
  `MOD_INGLES_PNBC`  ,
  `MOD_COMUNI_ESCRITA_PUNT`  ,
  `MOD_COMUNI_ESCRITA_DESEM`  ,
  `MOD_COMUNI_ESCRITA_PNAL`  ,
  `MOD_COMUNI_ESCRITA_PNBC`  ,
  `PUNT_GLOBAL`  ,
  `PERCENTIL_NBC`  ,
  `PERCENTIL_GLOBAL`  ,
  `ESTU_ESTADOINVESTIGACION`  ,
  '20191'
FROM sabertyt_genericas_20191
where 1 = 2;


#Seleccionar todas las columnas.
SELECT table_name, column_name
FROM information_schema.columns
WHERE table_schema = 'bd_analisis_datos_cdattg';

SELECT table_name
FROM information_schema.columns
WHERE table_schema = 'bd_analisis_datos_cdattg'
AND column_name LIKE 'COL%';

SELECT  column_name, count( column_name ) as conteo
FROM information_schema.columns
WHERE table_schema = 'bd_analisis_datos_cdattg'
group by column_name
order by table_name;



SELECT column1, column2, ...
INTO OUTFILE '/Users/sena/Desktop/archivo.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM tabla1
UNION ALL
SELECT column1, column2, ...
FROM tabla2
UNION ALL
-- Agrega más consultas SELECT para otras tablas si es necesario;

SELECT *
INTO OUTFILE '/Users/sena/Desktop/tmp/archivo.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM sabertyt_genericas_20182;

select * from sabertyt_genericas_20182 limit 100;
select column104 from sabertyt_genericas_20182 where trim(column104) <> '' limit 100;